# Generated by Django 2.1.1 on 2018-09-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmr_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rectangle',
        ),
    ]
